#!/bin/bash
source vars.txt
cd $tempDir
files=($(ls -v *))
for file in "${files[@]}"; do
    if [[ "$file" =~ [[:space:]] ]]; then
        mv "$file" "$(echo "$file" | tr ' ' '_')"
    fi
    if [[ "${file: -4}" == ".png" ]]; then
        mogrify -format jpg "$file"
        jpegFiles+=("${file%.png}.jpg")
    elif file_type=$(file -b --mime-type "$file"); then
        if [[ "$file_type" == "image/jpeg" ]]; then
            jpegFiles+=("$file")
        fi
    fi
done
if [ "${#jpegFiles[@]}" -eq 0 ]; then
    echo "No JPEG files found."
    exit 1
fi
RESULTS=$(IFS=' '; echo "${jpegFiles[*]}")
if [ -z "$1" ]; then
	echo -e "filename is unset!";
	img2pdf "${jpegFiles[@]}" --output "$tempDir/combined.pdf"
else
	flname=$1
	echo -e "filename is set to: '$flname'";
	img2pdf "${jpegFiles[@]}" --output "$tempDir/${flname}.pdf"
fi
