#!/bin/bash
source vars.txt
cd $tempDir
for file in *;
do
        if [[ "$file" =~ ( |\') ]]; then
               mv "$file" `echo $file | tr ' ' '_'` ;
        fi
done
############################################################
# Process the input options. Add options as needed.        #
############################################################
# Get the options
while getopts ":hpji" option; do
   case $option in
      h) # display Help
         echo "Welcome To The Help Dialog!"
	 echo -e "    -h\n      Brings up the Help Dialog; but you already know that :p"
	 echo -e "    -p\n      Converts pdfs into multiple pngs; once for each page of the originating pdf"
	 echo -e "    -j\n      Converts pdfs into multiple jpgs; once for each page of the originating pdf"
	 echo -e "    -i\n      Installs prerequisite packages!"
	 echo -e "    No Argument\n      Converts pdfs into multiple pngs and jpgs; once for each page of the originating pdf"
         exit;;
      p) #png only
         echo "Converting to png!"
	 RESULTS=$(ls -v | grep '.pdf')
	 for i in $RESULTS;
	 do
	 	 DIR=$(echo $i | cut -d. -f1)
                 mkdir "$DIR" 
		 COUNT=$(qpdf --show-npages $i)
		 for ((k = 1; k<=$COUNT; k++)); do
			 echo converting page: [$k/$COUNT]
			 inkscape $i --pdf-page=$k --export-type=png --export-filename=$k
		 done
		 mv *.png $DIR
	 done
         exit;;
      j) #jpg only... kinda not rly. inkscape has to convert to png first so we just silence the png related output
	 echo "Converting to jpg!"
	 RESULTS=$(ls -v | grep '.pdf')
         for i in $RESULTS;
         do
                 DIR=$(echo $i | cut -d. -f1)
                 mkdir "$DIR"
                 COUNT=$(qpdf --show-npages $i)
		 for ((k = 1; k<=$COUNT; k++)); do
			 echo converting page: [$k/$COUNT]
			 inkscape $i --pdf-page=$k --export-type=png --export-filename=$k
		 done
		 mv *.png $DIR
                 ls ./"$DIR"/*.png | xargs -I {} convert {} -quality 100 -density 300 {}.jpg
                 cd $DIR
                 P_RESULTS=$(ls *.png)
                 for p in $P_RESULTS;
		 do
		 	rm $p
		 done
		 J_RESULTS=$(ls *.jpg)
                 for j in $J_RESULTS
                 do
                        TMP=$(echo -e $j | cut -d. -f1)
                        mv $j $TMP.jpg
                 done
                 cd ../
         done
         exit;;
      i) #Install mode curently only works for Arch based distros with yay installed.
	 echo "Entering Install Mode!"
	 yay -Syu inkscape qpdf
         exit;;
   esac
done

if [ -z "$1" ]; then
	echo -e "Converting to png and jpg";
	RESULTS=$(ls -v | grep '.pdf')
	for i in $RESULTS;
	do
		DIR=$(echo $i | cut -d. -f1)
		mkdir "$DIR"
		COUNT=$(qpdf --show-npages $i)
		for ((k = 1; k<=$COUNT; k++)); do
			echo converting page: [$k/$COUNT]
			inkscape $i --pdf-page=$k --export-type=png --export-filename=$k
		done
		mv *.png $DIR
                ls ./"$DIR"/*.png | xargs -I {} convert {} -quality 100 -density 300 {}.jpg
		cd $DIR
		J_RESULTS=$(ls *.jpg)
		for j in $J_RESULTS
		do
			TMP=$(echo -e $j | cut -d. -f1)
			mv $j $TMP.jpg
		done
		cd ../
	done
else
	echo -e "ERROR: Unregognized flag variable!!!\nVariable recieved: $1\nFor usage information, Please run: pdf2jpg -h\n"
fi
